name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
        steps:
            - uses: actions/checkout@v3

            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: Build release binary
              run: |
                  cargo build --release --target ${{ matrix.target }}

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: scrippiscrappa-${{ matrix.target }}
                  path: |
                      target/${{ matrix.target }}/release/scrippiscrappa
                      target/${{ matrix.target }}/release/scrippiscrappa.exe
